"""Subclass of msg_emptyRequiredField, which is generated by wxFormBuilder."""

import wx
import Validations

# Implementing msg_emptyRequiredField
class msg_emptyRequiredField( Validations.msg_emptyRequiredField ):
	def __init__( self, parent ):
		Validations.msg_emptyRequiredField.__init__( self, parent )
	
	# Handlers for msg_emptyRequiredField events.
	def btn_okOnButtonClick( self, event ):
		self.Destroy()
	
	
