"""Subclass of msg_somethigWrong, which is generated by wxFormBuilder."""

import wx
import Validations

# Implementing msg_somethigWrong
class msg_somethigWrong(Validations.msg_somethigWrong):
	def __init__(self, parent,
				 msg=u'\n\nsomething went wrong while loading data into SQLite, \nplease check your input data'):
		Validations.msg_somethigWrong.__init__(self, parent, msg)
		self.parent = parent

	# Handlers for msg_somethigWrong events.
	def btn_okOnButtonClick(self, event):
		if self.parent:
			self.parent.Show()
		self.Close()

	def set_parent(self, obj):
		self.parent = obj
