"""Subclass of msg_registerCVs, which is generated by wxFormBuilder."""

import wx
import Validations

# Implementing msg_registerCVs
class msg_registerCVs( Validations.msg_registerCVs ):
	def __init__( self, parent ):
		Validations.msg_registerCVs.__init__( self, parent )
	
	# Handlers for msg_registerCVs events.
	def btn_okOnButtonClick( self, event ):
		self.Destroy()
	
