"""Subclass of msg_connSQLiteInvalid, which is generated by wxFormBuilder."""

import wx
import Validations

# Implementing msg_connSQLiteInvalid
class msg_connSQLiteInvalid( Validations.msg_connSQLiteInvalid ):
	def __init__( self, parent ):
		Validations.msg_connSQLiteInvalid.__init__( self, parent )
	
	# Handlers for msg_connSQLiteInvalid events.
	def btn_okOnButtonClick( self, event ):
		self.Destroy()