"""Subclass of dlg_VisulaizeWaMDaM, which is generated by wxFormBuilder."""

import wx
import Publish_Viz
from controller.ConnectDB_ParseExcel import DB_Setup
from viewer.Messages_forms.msg_somethigWrong import msg_somethigWrong

# Implementing dlg_VisulaizeWaMDaM
class dlg_VisulaizeWaMDaM( Publish_Viz.dlg_VisulaizeWaMDaM ):
	def __init__( self, parent ):
		Publish_Viz.dlg_VisulaizeWaMDaM.__init__( self, parent )
	
	# Handlers for dlg_VisulaizeWaMDaM events.
	def btn_UploadToOpenAguaOnButtonClick( self, event ):
		# TODO: Implement btn_UploadToOpenAguaOnButtonClick
		if not self.checkConnectingToSqlite():
			msg = "Warning: Please connect to sqlite."
			msg_somethigWrong(self, msg).Show()
		else:
			pass
		pass
	
	def btn_cancelOnButtonClick( self, event ):
		# TODO: Implement btn_cancelOnButtonClick
		self.Destroy()



	def checkConnectingToSqlite(self):
		db_setup = DB_Setup()
		if not db_setup.get_session():
			return False
		return True
	
	
