"""Subclass of msg_connSQLiteSuccs, which is generated by wxFormBuilder."""

import wx
import Validations

# Implementing msg_connSQLiteSuccs
class msg_connSQLiteSuccs( Validations.msg_connSQLiteSuccs ):
	def __init__( self, parent ):
		Validations.msg_connSQLiteSuccs.__init__( self, parent )
		self.parent = parent
	
	# Handlers for msg_connSQLiteSuccs events.
	def btn_okOnButtonClick( self, event ):
		if self.parent:
			self.parent.Show()
		self.Destroy()
	
	
