"""Subclass of msg_workbookInvalid, which is generated by wxFormBuilder."""

import wx
import Validations

# Implementing msg_workbookInvalid
class msg_workbookInvalid( Validations.msg_workbookInvalid ):
	def __init__( self, parent ):
		Validations.msg_workbookInvalid.__init__( self, parent )
	
	# Handlers for msg_workbookInvalid events.
	def btn_okOnButtonClick( self, event ):
		self.Destroy()
