"""Subclass of msg_selectWorkbokFirst, which is generated by wxFormBuilder."""

import wx
import Validations

# Implementing msg_selectWorkbokFirst
class msg_selectWorkbokFirst( Validations.msg_selectWorkbokFirst ):
	def __init__( self, parent ):
		Validations.msg_selectWorkbokFirst.__init__( self, parent )
	
	# Handlers for msg_selectWorkbokFirst events.
	def btn_okOnButtonClick( self, event ):
		self.Destroy()
	
	
