

from controller.Transform_utility.shapefileExporterFromShapefileInput import ShapefileExporterFromShapefileInput

from openpyxl import load_workbook
import xlrd as excel

shapefileExporterFromShapefileInputClass = ShapefileExporterFromShapefileInput('USDams_shapefile_converter_result.xlsx')

shapefileExporterFromShapefileInputClass.shapefileExporter('USDams_shapefile_converter_test.xlsx', 'Shapefile_input')