"""Subclass of dlg_ExtractWeapArea, which is generated by wxFormBuilder."""
import win32com.client

import wx
import ExportModels

# Implementing dlg_ExtractWeapArea
class dlg_ExtractWeapArea( ExportModels.dlg_ExtractWeapArea ):
	def __init__( self, parent ):
		ExportModels.dlg_ExtractWeapArea.__init__( self, parent )
	# Handlers for dlg_ExtractWeapArea events.
		list_code = []
		WEAP = win32com.client.Dispatch("WEAP.WEAPApplication")
		for area in WEAP.Areas:
			list_code.append(area.name)

		self.comboBox_WEAPArea.SetItems(list_code)

	def comboBox_WEAPAreaOnCombobox( self, event ):
		pass
		# TODO: Implement comboBox_WEAPAreaOnCombobox
		# first, make it as a drop down menu
		# second, get all the WEAP areas
		# WEAP = win32com.client.Dispatch("WEAP.WEAPApplication")
		# for area in WEAP.Areas:
		# 	Area_value = area.name

	def dirPicker_outputOnDirChanged( self, event ):
		# TODO: Implement dirPicker_outputOnDirChanged
		pass
	
	def btn_cancelOnButtonClick( self, event ):
		self.Destroy()

	
	def btn_exportOnButtonClick( self, event ):


		textCtrl_AreaNameOnText = self.comboBox_WEAPArea.Value


		fileDir = self.dirPicker_output.Path
		from controller.WEAP_exporter.ExtractWeapArea import WEAP_export
		weap_Export = WEAP_export(textCtrl_AreaNameOnText, fileDir)
		result_list, uniqObjectAtt_list = weap_Export.GetWEAPValues()
		# uniqObjectAtt_list = weap_Export.GetWEAPValues()
		weap_Export.SaveToExcel(result_list,uniqObjectAtt_list)
		# weap_Export.
		pass
	
	
