"""Subclass of dlg_SpecifyBoundary, which is generated by wxFormBuilder."""

import wx
import ExportModels

# Implementing dlg_SpecifyBoundary
class dlg_SpecifyBoundary( ExportModels.dlg_SpecifyBoundary ):
	def __init__( self, parent ):
		ExportModels.dlg_SpecifyBoundary.__init__( self, parent )
	
	# Handlers for dlg_SpecifyBoundary events.
	def textCtrl_LongMinOnText( self, event ):
		# TODO: Implement textCtrl_LongMinOnText
		pass
	
	def textCtrl_LongMaxOnText( self, event ):
		# TODO: Implement textCtrl_LongMaxOnText
		pass
	
	def textCtrl_LatMinOnTextEnter( self, event ):
		# TODO: Implement textCtrl_LatMinOnTextEnter
		pass
	
	def textCtrl_LatMaxOnText( self, event ):
		# TODO: Implement textCtrl_LatMaxOnText
		pass
	
	def btn_backOnButtonClick( self, event ):
		# import dlg_ProvideNetwork as fProvideNetwork
		# Serv = fProvideNetwork.dlg_ProvideNetwork(None)
		# Serv.ShowModal()
		self.Destroy()

	def btn_nextOnButtonClick( self, event ):
		import dlg_SelectRules as fdlg_dlg_SelectRules
		Serv = fdlg_dlg_SelectRules.dlg_SelectRules(None)
		Serv.ShowModal()



