"""Subclass of dlg_SelectModel, which is generated by wxFormBuilder."""

import wx
import ExportModels

# Implementing dlg_SelectModel
class dlg_SelectModel( ExportModels.dlg_SelectModel ):
	def __init__( self, parent ):
		ExportModels.dlg_SelectModel.__init__( self, parent )
	
	# Handlers for dlg_SelectModel events.
	def comboBox_SelectModelOnCombobox( self, event ):
		# TODO: Implement comboBox_SelectModelOnCombobox
		pass
	
	def btn_addmodelOnButtonClick( self, event ):
		# TODO: Implement btn_addmodelOnButtonClick
		pass
	
	def btn_cancelOnButtonClick( self, event ):
		self.Destroy()

	
	def btn_nextOnButtonClick( self, event ):
		import dlg_ProvideNetwork as fProvideNetwork
		Serv = fProvideNetwork.dlg_ProvideNetwork(None)
		Serv.ShowModal()

	
