"""Subclass of dlg_ServeToWEAP, which is generated by wxFormBuilder."""

import wx
import ExportModels

# Implementing dlg_ServeToWEAP
class dlg_ServeToWEAP( ExportModels.dlg_ServeToWEAP ):
	def __init__( self, parent ):
		ExportModels.dlg_ServeToWEAP.__init__( self, parent )
	
	# Handlers for dlg_ServeToWEAP events.
	def comboBox_SelectModelOnCombobox( self, event ):
		# TODO: Implement comboBox_SelectModelOnCombobox
		pass
	
	def btn_serveOnButtonClick( self, event ):
		# TODO: Implement btn_serveOnButtonClick
		pass
	
	def btn_cancelOnButtonClick( self, event ):
		# TODO: Implement btn_cancelOnButtonClick
		pass
	
	
