"""Subclass of dlg_SelectRules, which is generated by wxFormBuilder."""

import wx
import ExportModels

# Implementing dlg_SelectRules
class dlg_SelectRules( ExportModels.dlg_SelectRules ):
	def __init__( self, parent ):
		ExportModels.dlg_SelectRules.__init__( self, parent )
	
	# Handlers for dlg_SelectRules events.
	def comboBox_ruleOnCombobox( self, event ):
		# TODO: Implement comboBox_ruleOnCombobox
		pass
	
	def m_button20OnButtonClick( self, event ):
		# TODO: Implement m_button20OnButtonClick
		pass

	def dirPicker_python_outputOnDirChanged( self, event ):
		# TODO: Implement dirPicker_python_outputOnDirChanged
		pass
	
	def btn_backOnButtonClick( self, event ):
		# import dlg_SpecifyBoundary as fdlg_SpecifyBoundary
		# Serv = fdlg_SpecifyBoundary.dlg_SpecifyBoundary(None)
		# Serv.ShowModal()
		self.Destroy()
	def btn_exportOnButtonClick( self, event ):
		# self.Destroy()
		self.Close()
	
