"""Subclass of dlg_re_run_export, which is generated by wxFormBuilder."""

import wx
import ExportModels

# Implementing dlg_re_run_export
class dlg_re_run_export( ExportModels.dlg_re_run_export ):
	def __init__( self, parent ):
		ExportModels.dlg_re_run_export.__init__( self, parent )
	
	# Handlers for dlg_re_run_export events.
	def btn_backOnButtonClick( self, event ):
		self.Close()
	
	def btn_exportOnButtonClick( self, event ):
		self.Close()
	
	
