"""Subclass of dlg_Help, which is generated by wxFormBuilder."""

import wx
import WaMDaMWizard

# Implementing dlg_Help
class dlg_Help( WaMDaMWizard.dlg_Help ):
	def __init__( self, parent ):
		WaMDaMWizard.dlg_Help.__init__( self, parent )
	
	# Handlers for dlg_Help events.
	def sdbSizer_AboutOKOnOKButtonClick( self, event ):
		self.Destroy()
	
	
