"""Subclass of dlg_ImportSpreadsheetAdvanced, which is generated by wxFormBuilder."""

import wx
import WaMDaMWizard

# Implementing dlg_ImportSpreadsheetAdvanced
class dlg_ImportSpreadsheetAdvanced( WaMDaMWizard.dlg_ImportSpreadsheetAdvanced ):
	def __init__( self, parent ):
		WaMDaMWizard.dlg_ImportSpreadsheetAdvanced.__init__( self, parent )
	
	# Handlers for dlg_ImportSpreadsheetAdvanced events.
	def checkBox_DatasetTOnCheckBox( self, event ):
		# TODO: Implement checkBox_DatasetTOnCheckBox
		pass
	
	def checkBox_ObjectTypesTOnCheckBox( self, event ):
		# TODO: Implement checkBox_ObjectTypesTOnCheckBox
		pass
	
	def checkBox_ObjectCategoryTOnCheckBox( self, event ):
		# TODO: Implement checkBox_ObjectCategoryTOnCheckBox
		pass
	
	def checkBox_AttributesTOnCheckBox( self, event ):
		# TODO: Implement checkBox_AttributesTOnCheckBox
		pass
	
	def checkBox_AttributeCategoryTOnCheckBox( self, event ):
		# TODO: Implement checkBox_AttributeCategoryTOnCheckBox
		pass
	
	def checkBox_ObjectAttributesTOnCheckBox( self, event ):
		# TODO: Implement checkBox_ObjectAttributesTOnCheckBox
		pass
	
	def checkBox_NetworksTOnCheckBox( self, event ):
		# TODO: Implement checkBox_NetworksTOnCheckBox
		pass
	
	def checkBox_ScenariosTOnCheckBox( self, event ):
		# TODO: Implement checkBox_ScenariosTOnCheckBox
		pass
	
	def checkBox_NodesTOnCheckBox( self, event ):
		# TODO: Implement checkBox_NodesTOnCheckBox
		pass
	
	def checkBox_LinksTOnCheckBox( self, event ):
		# TODO: Implement checkBox_LinksTOnCheckBox
		pass
	
	def checkBox_OrganizationsPeopleTOnCheckBox( self, event ):
		# TODO: Implement checkBox_OrganizationsPeopleTOnCheckBox
		pass
	
	def checkBox_MethodsTOnCheckBox( self, event ):
		# TODO: Implement checkBox_MethodsTOnCheckBox
		pass
	
	def checkBox_SourcesTOnCheckBox( self, event ):
		# TODO: Implement checkBox_SourcesTOnCheckBox
		pass
	
	def checkBox_BinaryTOnCheckBox( self, event ):
		# TODO: Implement checkBox_BinaryTOnCheckBox
		pass
	
	def checkBox_ParametersTOnCheckBox( self, event ):
		# TODO: Implement checkBox_ParametersTOnCheckBox
		pass
	
	def checkBox_SeasonalParametersTOnCheckBox( self, event ):
		# TODO: Implement checkBox_SeasonalParametersTOnCheckBox
		pass
	
	def checkBox_DescriptorValuesTOnCheckBox( self, event ):
		# TODO: Implement checkBox_DescriptorValuesTOnCheckBox
		pass
	
	def checkBox_TextFreeTOnCheckBox( self, event ):
		# TODO: Implement checkBox_TextFreeTOnCheckBox
		pass
	
	def checkBox_FileBasedTOnCheckBox( self, event ):
		# TODO: Implement checkBox_FileBasedTOnCheckBox
		pass
	
	def checkBox_TimeSereisTOnCheckBox( self, event ):
		# TODO: Implement checkBox_TimeSereisTOnCheckBox
		pass
	
	def checkBox_MultiColumnsArraysTOnCheckBox( self, event ):
		# TODO: Implement checkBox_MultiColumnsArraysTOnCheckBox
		pass
	
	def btn_LoadTablesOnButtonClick( self, event ):
		# TODO: Implement btn_LoadTablesOnButtonClick
		pass
	
	def btn_doneOnButtonClick( self, event ):
		self.Destroy()
	
	
