"""Subclass of dlg_CrossTabTimeSeriesToWaMDaM, which is generated by wxFormBuilder."""

import wx, define
import WaMDaMWizard
from Messages_forms.msg_somethigWrong import msg_somethigWrong
from controller.timeSeriesData_shaper import TimeSeriesDataShaper
# Implementing dlg_CrossTabTimeSeriesToWaMDaM
class dlg_CrossTabTimeSeriesToWaMDaM( WaMDaMWizard.dlg_CrossTabTimeSeriesToWaMDaM ):
    def __init__( self, parent ):
        WaMDaMWizard.dlg_CrossTabTimeSeriesToWaMDaM.__init__( self, parent )
        self.cross_file = None

    # Handlers for dlg_CrossTabTimeSeriesToWaMDaM events.
    def FilePicker_RwiseFileOnFileChanged( self, event ):
        # TODO: Implement FilePicker_RwiseFileOnFileChanged
        self.cross_file = self.FilePicker_CrossTabTimeSeriesToWaMDaM.GetPath()
        valid_extension = ['xlsx','xlsm']
        if not (self.cross_file.split('.')[-1] in valid_extension):
            self.Destroy()
            message = msg_somethigWrong(None, msg="A non excel file was selected, \n\n"
                                                  " Please select a valid Excel File")
            message.Show()

    def btn_ConvertCrossTabTimeSeriesToWaMDaMOnButtonClick( self, event ):
        # TODO: Implement btn_ConvertCrossTabTimeSeriesToWaMDaMOnButtonClick
        define.logger = define.create_logger(self.cross_file.split('\\')[-1].split('.')[0])
        define.logger.name = __name__
        define.logger.info("Start time series data convert.")

        if self.cross_file:
            try:
                TimeSeriesDataShaper(workbook=self.cross_file)
                self.allDone()
                define.logger.info("Series data convert was finished successfully.")
                # self.Destroy()
            except Exception as e:
                define.logger.error('Failed time series data convert.\n' + e.message)
                from Messages_forms.generalMsgDlg import messageDlg
                msgDlg = messageDlg(None)
                msgDlg.SetTitle("Sorry: something went wrong")
                msgDlg.setMessage(e.message)
                # message = msg_somethigWrong(None, msg=u'{}, \n\n[*] Could not complete CrossTabulated Task'.format(e))
                msgDlg.Show()
        else:
            from Messages_forms.msg_selectWorkbokFirst import msg_selectWorkbokFirst

            instance = msg_selectWorkbokFirst(None)
            result = instance.ShowModal()
            instance.Destroy()

    def btn_cancelOnButtonClick( self, event ):
        self.Destroy()

    def allDone(self):
        from Messages_forms.generalMsgDlg import messageDlg

        instance = messageDlg(None)
        instance.SetTitle(u"Successfully loaded data")
        # instance.Show()
        instance.setMessage(u"\n\nYou successfully loaded '" + self.cross_file.split('\\')[-1] + u"'.")
        result = instance.ShowModal()
        instance.Destroy()
        self.Destroy()


