"""Subclass of msg_selectDatabaseFirst, which is generated by wxFormBuilder."""

import wx
import Validations

# Implementing msg_selectDatabaseFirst
class msg_selectDatabaseFirst( Validations.msg_selectDatabaseFirst ):
	def __init__( self, parent ):
		Validations.msg_selectDatabaseFirst.__init__( self, parent )
	
	# Handlers for msg_selectDatabaseFirst events.
	def btn_okOnButtonClick( self, event ):
		self.Destroy()
	
	
