"""Subclass of msg_dependencyViolation, which is generated by wxFormBuilder."""

import wx
import Validations

# Implementing msg_dependencyViolation
class msg_loading( Validations.msg_loading ):
	def __init__( self, parent ):
		Validations.msg_loading.__init__( self, parent )

	# Handlers for msg_dependencyViolation events.
	def btn_okOnButtonClick( self, event ):
		self.Destroy()

	def load_guage(self, val):
		self.guage.SetValue(val)

	def btn_cancelOnButtonClick(self, event):
		raise Exception("Please Stop loading!")
