"""Subclass of msg_duplicateEnties, which is generated by wxFormBuilder."""

import wx
import Validations

# Implementing msg_duplicateEnties
class msg_duplicateEnties( Validations.msg_duplicateEnties ):
	def __init__( self, parent ):
		Validations.msg_duplicateEnties.__init__( self, parent )
	
	# Handlers for msg_duplicateEnties events.
	def btn_okOnButtonClick( self, event ):
		self.Destroy()
	
