"""Subclass of dlg_ShapefileToWaMDaM, which is generated by wxFormBuilder."""

import wx
import WaMDaMWizard, threading
from Messages_forms.msg_somethigWrong import msg_somethigWrong
from controller.shapefileExporter import shapefileExporter

# Implementing dlg_ShapefileToWaMDaM
class dlg_ShapefileToWaMDaM( WaMDaMWizard.dlg_ShapefileToWaMDaM ):
    def __init__( self, parent ):
        WaMDaMWizard.dlg_ShapefileToWaMDaM.__init__( self, parent )
        self.shape_file = None

    # Handlers for dlg_ShapefileToWaMDaM events.
    def FilePicker_ShapefileToWaMDaMOnFileChanged( self, event ):
        # TODO: Implement FilePicker_ShapefileToWaMDaMOnFileChanged
        self.shape_file = self.FilePicker_ShapefileToWaMDaM.GetPath()
        valid_extension = ['xlsx','xlsm']
        if not (self.shape_file.split('.')[-1] in valid_extension):
            self.Destroy()
            message = msg_somethigWrong(None, msg="A non excel file was selected, \n\n"
                                                  " Please select a valid EXCEL File")
            message.Show()

    def btn_ConvertShapefileDataOnButtonClick( self, event ):
        # TODO: Implement btn_ConvertShapefileDataOnButtonClick
        if self.shape_file:
            try:
            # Show a msg to tell the user to wait.
                from viewer.Messages_forms.generalMsgDlg import messageDlg
                self.waiting_dlg = messageDlg(None)
                self.waiting_dlg.btn_OK.Shown = False
                self.waiting_dlg.Title = "Loading Data..."
                self.waiting_dlg.setMessage("Please wait a moment still loading is done.")
                self.waiting_dlg.Show()
            #///////////////////////////////////////////////////////////////////////#

            # Start thread to load data
                our_thread = threading.Thread(None, self.load_data)
                our_thread.start()
            #///////////////////////////////////////////////////////////////////////#


                # self.Destroy()
            except Exception as e:
                message = msg_somethigWrong(None, msg=u'{}, \n\n[*] Could not complete ShapeFile Task'.format(e))
                message.Show()
        else:
            from Messages_forms.msg_selectWorkbokFirst import msg_selectWorkbokFirst

            instance = msg_selectWorkbokFirst(None)
            result = instance.ShowModal()
            instance.Destroy()
            # instance.Show()
    def load_data(self):
        shapefileExporter(workbook=self.shape_file)

    # Call allDone method once loading is done
        wx.CallAfter(self.allDone)
    #//////////////////////////////////////////
    def allDone(self):
        self.waiting_dlg.Destroy()
        from Messages_forms.generalMsgDlg import messageDlg

        instance = messageDlg(None)
        instance.SetTitle(u"Successfully loaded data")
        # instance.Show()
        instance.setMessage(u"Conversion was Successful. Please find the results in the excel file '{}'.".format(self.shape_file))
        result = instance.ShowModal()
        instance.Destroy()
        self.Destroy()
    def btn_cancelOnButtonClick( self, event ):
        self.Destroy()
