"""Subclass of dlg_About, which is generated by wxFormBuilder."""

import wx
import WaMDaMWizard

# Implementing dlg_About
class dlg_About( WaMDaMWizard.dlg_About ):
	def __init__( self, parent ):
		WaMDaMWizard.dlg_About.__init__( self, parent )
	
	# Handlers for dlg_About events.
	def sdbSizer_AboutOKOnOKButtonClick( self, event ):
		self.Destroy()
	
	
